name: PyTorch Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run commands in PyTorch container
      uses: docker://pytorch/pytorch:2.2.0-cuda11.8-cudnn8-devel
      with:
        entrypoint: /bin/bash
        args: -c "cat /etc/os-release && lld -version"
